config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home' #home page view at root
  get 'about', to: 'pages#about' #about page view
  resources :articles # all routes for articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/user.rb
require 'valid_email'

class User <    ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    
    validates :username, 
        presence: true, 
        uniqueness: { case_sensitive: false}, 
        length: { minimum:3, maximum:25 }
    validates :email, 
        presence: true, 
        uniqueness: { case_sensitive: false}, 
        length: { maximum:105 },
        email: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
       !!current_user 
    end
    
    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    
    
    def show
    end
    
    
    
    
    def index
        @articles = Article.paginate(page: params[:page], per_page: 8)
    end
    
    
    
    
    def edit
    end
    
    
    
    
    def new
        @article = Article.new
    end
    
    
    
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        
        respond_to do |format|
            if @article.save
                format.html {redirect_to @article, notice: 'Article was created successfully' }
            else
                format.html {render :new, status: :unprocessable_entity}
            end
        end
    end
    
    
    
    
    def update
        
            respond_to do |format|
                if @article.update(article_params)
                    format.html {redirect_to @article, notice: 'Article was updated successfully' }
                else
                    format.html {render :edit, status: :unprocessable_entity}
                end
            end
    end
    
    
    
    def destroy
        @article.destroy
        redirect_to articles_path
    end
    
    
    
    private
    
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description)
    end
    
    def require_same_user
        if current_user != @article.user
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    # home page method
    def home
        
    end
    
    # about page method
    def about
        
    end
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        # @user = User.new
    end

    def create 
        user = User.find_by(username: params.dig(:session,:username))
        
         respond_to do |format|
            if user && user.authenticate(params[:session][:password])
                session[:user_id] = user.id
                format.html {redirect_to user, notice: "Logged in successfully" }
            else
                format.html {redirect_to login_path, alert: "Incorrect Login", status: :unprocessable_entity}
            end
        end
        
    end
    
    def destroy
        respond_to do |format|
            session[:user_id] = nil
            format.html {redirect_to root_path, notice: "Logged Out" }
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 3)
    end
    
    def index
        @users = User.paginate(page: params[:page], per_page: 4)
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)

        respond_to do |format|
            if @user.save
                session[:user_id] = @user.id
                format.html {redirect_to articles_path, :notice => 'Welcome to Bloggie Blog ' + @user.username + ', you have successfully signed up' }
            else
                format.html {render :new, status: :unprocessable_entity}
            end
        end
    end
    
    def destroy
        @user.destroy
        respond_to do |format|
            reset_session
            format.html {redirect_to articles_path, notice: "Account and all associated articles successfully deleted", status: :see_other}
        end
    end
    
    
    
    def edit
        
    end
    
    
    def update
        respond_to do |format|
            if @user.update(user_params)
                format.html {redirect_to user_path, notice: 'Account was updated successfully' }
            else
                format.html {render :edit, status: :unprocessable_entity}
            end
        end
    end    
     
     
     
     
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
        
    def require_same_user
        if current_user != @user
            flash[:alert] = "You can only edit or delete your own account"
            redirect_to @user
        end
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(user, options = { size:80 })
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "author-image")
    end
    

    
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<%= form_with(model: @article, local: true) do |f|%>

<!--Title-->
<div class="row">
    <div class="col-lg-3">
        <div class="title-write">
            <p>Title</p>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="write-content-box title-input">
            <%= f.text_field :title, :placeholder => "Enter your title here" %>
        </div>
    </div>
</div>

<!--Description-->
<div class="row">
    <div class="col-lg-3">
        <div class="title-write">
            <p>Description</p>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="write-content-box">
            <%= f.text_area :description, rows:15, placeholder:"Lorem Ipsum and All That Jazzzzzzzzzzzzzzz." %>
        </div>
    </div>
</div>

<!--Tags-->
<div class="row">
    <div class="col-lg-3">
        <div class="title-write">
            <p>Tags</p>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="write-content-box tags-radio d-flex justify-content-around">
            <!--business-->
            <input type="radio" id="radio-business" value="business" name="tag">
            <label for="radio-business" class="business">Business</label>
            <!--travel-->
            <input type="radio" id="radio-travel" value="travel" name="tag">
            <label for="radio-travel" class="travel">Travel</label>
            <!--health-->
            <input type="radio" id="radio-health" value="health" name="tag">
            <label for="radio-health" class="health">Health</label>
            <!--technology-->
            <input type="radio" id="radio-tech" value="tech" name="tag">
            <label for="radio-tech" class="tech">Tech</label>
        </div>
    </div>
</div>

<hr>

<!--Buttons-->
<div class="conditon-buttom-wrap">

    <div class="button-box">
        <%= f.submit class:"btn-large btn-primary" %>
        <%= link_to 'Cancel', articles_path, class:"btn-large btn-secondary"%>
    </div>
</div>
<% end %>

app/views/articles/edit.html.erb
<div class="share-your-thinking-area">
    <div class="container">
        
        <div class="row section-space--pb_60">
            <div class="col-12">
                <div class="share-thinking-title">
                    <h2 class="title text-center">Edit Article</h2>
                </div>
            </div>
        </div>


          <%= render 'form' %>


    </div>
</div>

app/views/articles/index.html.erb
<div class="blog-details-wrapper">
    <div class="container">
        <!--Title-->
        <div class="row section-space--pb_60">
            <div class="col-12">
                <div class="share-thinking-title text-center">
                    <h2 class="title">Articles</h2>
                </div>
            </div>
        </div>
        <!--Article Grid-->
        <div class="row row--17">
            <% @articles.each do |article| %>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <!-- Single Following Post Start -->
                <div class="single-following-post"> <!-- data-aos="fade-up" -->
                    <%= link_to article_path(article), class:"following-post-thum" do %>
                        <%= image_tag("blog/01.jpg", :alt => "meditation") %>
                    <% end %>
                    <div class="following-post-content">
                        <div class="following-blog-post-top">
                            <div class="trending-blog-post-category">
                                <a href="#" class="business">Business</a>
                            </div>
                            <div class="following-blog-post-author">
                                By <%= link_to article.user.username, user_path(article.user) %>
                            </div>
                        </div>
                        <h5 class="following-blog-post-title">
                            <%= link_to article.title,  article_path(article) %>
                        </h5>
                        <p> <%= truncate(article.description, length:50) %> </p>
                        <div class="following-blog-post-meta">
                            <div class="post-meta-left-side">
                                <span class="post-date">
                                   <%= article.created_at.strftime("%B %d, %Y") %>
                                </span>
                            </div>
                            <div class="post-meta-right-side">
                                <% if logged_in? && article.user == current_user %>
                                    <%= link_to edit_article_path(article) do%><i class="icofont-edit-alt"></i><% end %>
                                    <%= link_to article_path(article), data: {"turbo-method": :delete, "turbo-confirm": "Are you sure?" } do%><i class="icofont-ui-delete"></i><% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div><!-- Single Following Post End -->
            </div>
            <% end %>
            
            
            <div class="col-lg-4 col-md-6 col-sm-6 d-flex justify-content-center align-items-center">
                <%= link_to new_article_path do %>
                    <div class="btn-primary btn-large">
                        Create new article <i class="icofont-plus"></i>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="testimonial-slider-navigation-two">
            <%= will_paginate @articles, 
                list_classes: %w(pagination justify-content-center border-0), 
                :page_links => false, 
                :previous_label => '<div class="testimonial-button-next navigation-button"><i class="icofont-long-arrow-left"></i></div>',
                :next_label => '<div class="testimonial-button-prev navigation-button"><i class="icofont-long-arrow-right"></i></div>'
            %>
        </div>
    </div>
</div> <!-- Blog Details Wrapper End -->

app/views/articles/new.html.erb
<div class="share-your-thinking-area">
    <div class="container">
        
        <div class="row section-space--pb_60">
            <div class="col-12">
                <div class="share-thinking-title">
                    <h2 class="title text-center">Create New Article</h2>
                </div>
            </div>
        </div>

        <%= render 'form' %>
        
    </div>
</div>

app/views/layouts/_header.html.erb
<!--========  Header Area =========-->
    <header class="header">
        <div class="header-mid-area">
            <div class="container">
                <div class="row align-items-center">
                    <!--Logo-->
                    <div class="col-lg-3 col-md-2 col-5">
                        <div class="logo">
                            <%= link_to image_tag("logo/logo.png", :alt => "Bloggie Blog Logo"), root_path %>
                        </div>
                    </div>
                    <!--Advertisement-->
                    <div class="col-lg-6 col-md-6 d-md-block d-none">
                        <div class="header-add-banner text-center">
                           <%= link_to root_path do%>
                                <%= image_tag "banners/header-add-banner.jpg" %>
                                <h6 class="header-add-text">All Food Item
                                  <span>50% Off</span>
                                </h6>
                           <% end %>   
                        </div>
                    </div>
                    <!--Sign Up / Log In Top Right Icons-->
                    <div class="col-lg-3 col-md-4 col-7">
                        <div class="header-mid-right-side">
                            <% if logged_in? %>
                                <%= link_to 'Log Out', logout_path,data: {"turbo-method": :delete}, class:"btn-primary btn-large me-0" %>
                            <% else %>
                                <%= link_to 'Sign Up', signup_path, class:"btn-primary btn-large me-0" %>
                            <% end %>

                        </div>
                  </div>
                </div>
            </div>
        </div>
        <div class="header-bottom-area">
            <div class="container">
                <div class="row align-items-center">
                    <!--Social Icons-->
                    <div class="col-lg-4 col-9">
                        <ul class="social-share-area mt-15 mb-15">
                            <li><%= link_to "https://www.facebook.com", :target => "_blank" do%><i class="icofont-facebook"></i><% end %></li>                            
                            <li><%= link_to "https://www.instagram.com", :target => "_blank" do%><i class="icofont-instagram"></i><% end %></li>                            
                            <li><%= link_to "https://www.twitter.com", :target => "_blank" do%><i class="icofont-twitter"></i><% end %></li>                            
                            <li><%= link_to "https://www.linkedin.com", :target => "_blank" do%><i class="icofont-linkedin"></i><% end %></li>                              
                        </ul>
                    </div>
                    <div class="col-lg-8 col-3">
                        <div class="main-menu-area text-end">
                            <nav class="navigation-menu">
                                <ul>
                                    <!--Home-->
                                    <li> <!-- class="has-children" -->
                                        <%= link_to root_path do%><span>Home</span><% end %>
                                        <!-- <ul class="submenu">
                                            <li><a href="index-2.html"><span>Home Two</span></a></li>
                                            <li><a href="index-3.html"><span>Home Three</span></a></li>
                                            <li><a href="index-4.html"><span>Home Four</span></a></li>
                                            <li><a href="index-5.html"><span>Home Five</span></a></li>
                                            <li><a href="index-6.html"><span>Home Six</span></a></li>
                                        </ul> -->
                                    </li>
                                    <!--About-->
                                    <li>
                                        <%= link_to users_path do%><span>About</span><% end %>
                                    </li>
                                    <!--Articles-->
                                    <li class="has-children" >
                                        <!--<a><span>Articles</span></a>-->
                                        <%= link_to articles_path do%><span>Articles</span><% end %>
                                        <ul class="submenu">
                                            <li><%= link_to articles_path do%><span>View Articles</span><% end %></li>
                                            <% if logged_in? %>
                                                <li><%= link_to new_article_path do%><span>Create New Article</span><% end %></li>
                                            <% end %>
                                        <!--    <li><%= link_to articles_path do%><span>Travel</span><% end %></li>-->
                                        <!--    <li><%= link_to articles_path do%><span>Health</span><% end %></li>-->
                                        <!--    <li><%= link_to articles_path do%><span>Tech</span><% end %></li>-->
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <!-- mobile menu -->
                        <div class="mobile-menu-right">
                            <div class="mobile-navigation-icon d-block d-lg-none" id="mobile-menu-trigger">
                                <i></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--======== End of Header Area  =========-->
    
<!--====================  mobile menu overlay ====================-->
    <div class="mobile-menu-overlay" id="mobile-menu-overlay">
        <div class="mobile-menu-overlay__inner">
            <div class="mobile-menu-overlay__header">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-md-6 col-8">
                            <!-- logo -->
                            <div class="logo">
                                <%= link_to image_tag("logo/logo.png", :alt => "Bloggie Blog Logo"), root_path %>
                            </div>
                        </div>
                        <div class="col-md-6 col-4">
                            <!-- mobile menu content -->
                            <div class="mobile-menu-content text-end">
                                <span class="mobile-navigation-close-icon" id="mobile-menu-close-trigger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mobile-menu-overlay__body">
                <nav class="offcanvas-navigation">
                    <ul>
                        <!--Home-->
                        <li> <!-- class="has-children" -->
                            <%= link_to root_path do%><span>Home</span><% end %>
                            <!-- <ul class="submenu">
                                <li><a href="index-2.html"><span>Home Two</span></a></li>
                                <li><a href="index-3.html"><span>Home Three</span></a></li>
                                <li><a href="index-4.html"><span>Home Four</span></a></li>
                                <li><a href="index-5.html"><span>Home Five</span></a></li>
                                <li><a href="index-6.html"><span>Home Six</span></a></li>
                            </ul> -->
                        </li>
                        <!--About-->
                        <li>
                            <%= link_to users_path do%><span>About</span><% end %>
                        </li>
                            <!--Articles-->
                            <li class="has-children" >
                                <%= link_to articles_path do%><span>Articles</span><% end %>
                                <ul class="submenu">
                                    <li><%= link_to articles_path do%><span>View Articles</span><% end %></li>
                                    <li><%= link_to new_article_path do%><span>Create New Article</span><% end %></li>
                                <!--    <li><%= link_to articles_path do%><span>Travel</span><% end %></li>-->
                                <!--    <li><%= link_to articles_path do%><span>Health</span><% end %></li>-->
                                <!--    <li><%= link_to articles_path do%><span>Tech</span><% end %></li>-->
                                </ul>
                            </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!--====================  End of mobile menu overlay  ====================-->

app/views/layouts/_messages.html.erb
<div class="share-your-thinking-area">
    <div class="container">  
  
    <% flash.each do |name, msg| %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    
  </div>
</div>

app/views/pages/about.html.erb
<h1>This is the About Page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home Page', root_path %> 

app/views/pages/home.html.erb
<%= render 'layouts/hero' %>

app/views/users/show.html.erb
<div class="blog-details-wrapper section-space--pb_60">
    <div class="container">
        
        <div class="row row--17">
                <!--<div class="share-thinking-title">-->
                <!--    <h2 class="title text-center"><%= @user.username %>'s Profile</h2>-->
                <!--    </div>-->
                        <div class="blog-details-col-8">

                            <!--<div class="messonry-button section-space--mb_40">-->
                            <!--    <button data-filter="*" class="is-checked"><span class="filter-text">All</span></button>-->
                            <!--    <button data-filter=".cat--1"><span class="filter-text">Travel</span> </button>-->
                            <!--    <button data-filter=".cat--2"><span class="filter-text">Lifestyle</span></button>-->
                            <!--    <button data-filter=".cat--3"><span class="filter-text">Food</span> </button>-->
                            <!--    <button data-filter=".cat--4"><span class="filter-text">Health</span></button>-->
                            <!--</div>-->

                            <div class="masonry-activation">
                                <div class="row mesonry-list">
                                    <div class="masonary-sizer col-1"></div>
                                    <!-- Author Blog Post Wrap Start -->
                                    <% @articles.each do |article| %>
                                    <div class="author-blog-post-wrap masonary-item cat--3">
                                        <a href="blog-details.html" class="author-blog-thum">
                                            <%= link_to article_path(article), class:"following-post-thum" do %>
                                                <%= image_tag("blog/blog-details-1.jpg", :alt => "meditation") %>
                                            <% end %>
                                        </a>
                                        <div class="author-blog-post-content">
                                            <div class="blog-details-meta-box">
                                                <div class="post-meta-left-side mb-2">
                                                    <div class="blog-post-category">
                                                        <a href="#" class="btn-medium business mr-1">Business</a>
                                                    </div>
                                                    <div class="blog-post-author">
                                                        By <%= article.user.username if article.user %>                                                    
                                                    </div>
                                                </div>
                                                <div class="post-right-side mb-2">
                                                    <span class="post-meta-left-side">
                                                    <span class="post-date">
                                                        <%= article.created_at.strftime("%B %d, %Y") %>
                                                    </span>
                                                    </span>
                                                </div>
                                            </div>
                                            <h3 class="title mb-2">
                                                <%= link_to article.title,  article_path(article) %>
                                            </h3>
                                            <p class="mb-2"><%= simple_format(article.description) %></p>

                                            <% if logged_in? and @user == current_user %>
                                            <div class="author-post-action-box justify-content-end">
                                                <div class="author-post-action-box">
                                                    <div class="author-action">
                                                        <%= link_to edit_article_path(article) do%><i class="icofont-edit-alt"></i><% end %>
                                                    </div>
                                                    <div class="author-action">
                                                        <%= link_to article_path(article), data: {"turbo-method": :delete, "turbo-confirm": "Are you sure?" } do%><i class="icofont-ui-delete"></i><% end %>
                                                    </div>
                                                </div>
                                            </div>
                                            <% end %>
                                        </div>
                                    </div><!-- Author Blog Post Wrap End -->
                                    <% end %>
                                
                                </div>
                            </div>
                        </div>
                        
                        <!-- Author Area-->
                        <div class="blog-details-col-4 sticky-top">
                            <div class="following-author-area">
                                <!--<div class="author-image" data-aos="fade-up">-->
                                    <%= gravatar_for @user, size:200 %>
                                <!--</div>-->
                                <div class="author-title">
                                    <h4><%= @user.username %></h4>
                                    <!--<p>Author, Dani Hooven</p>-->
                                </div>
                                <div class="author-details">
                                    <p>I am a kind and interesting person.</p>
                                    <% if logged_in? and @user == current_user %>
                                        <div class="pb-5">
                                            <%= link_to edit_user_path(@user) do%><i class="icofont-edit-alt"></i><% end %>
                                            <%= link_to user_path(current_user), data: {"turbo-method": :delete, "turbo-confirm": "Are you sure?" } do%><i class="icofont-ui-delete"></i><% end %>
                                        </div>
                                    <% end %>
                                    <div class="author-post-share">
                                        <ul class="social-share-area">
                                            <li><%= link_to "https://www.facebook.com", :target => "_blank" do%><i class="icofont-facebook"></i><% end %></li>                            
                                            <li><%= link_to "https://www.instagram.com", :target => "_blank" do%><i class="icofont-instagram"></i><% end %></li>                            
                                            <li><%= link_to "https://www.twitter.com", :target => "_blank" do%><i class="icofont-twitter"></i><% end %></li>                            
                                            <li><%= link_to "https://www.linkedin.com", :target => "_blank" do%><i class="icofont-linkedin"></i><% end %></li>     
                                        </ul>
                                    </div>
                                    <!--<div class="button-box">-->
                                    <!--    <a href="#" class="btn">View Profile <i class="icofont-long-arrow-right"></i></a>-->
                                    <!--</div>-->
                                </div>
                            </div>
                        
                    
                    

            </div>
        </div>
            <div class="testimonial-slider-navigation-two pt-2">
                <%= will_paginate @articles, 
                    list_classes: %w(pagination justify-content-center border-0), 
                    :page_links => false, 
                    :previous_label => '<div class="testimonial-button-next navigation-button"><i class="icofont-long-arrow-left"></i></div>',
                    :next_label => '<div class="testimonial-button-prev navigation-button"><i class="icofont-long-arrow-right"></i></div>'
                %>
            </div>
        
        
    </div>
</div>